package medicremaster;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.dynamicreports.examples.Templates;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import static net.sf.dynamicreports.report.builder.DynamicReports.cmp;
import static net.sf.dynamicreports.report.builder.DynamicReports.sbt;
import static net.sf.dynamicreports.report.builder.DynamicReports.stl;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.component.ComponentBuilder;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.component.HorizontalListBuilder;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalTextAlignment;
import net.sf.dynamicreports.report.constant.VerticalTextAlignment;
import net.sf.dynamicreports.report.exception.DRException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ranjeet
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     * 
     */
    
    ResultSet rs=null;
    PreparedStatement sel;
    
    MyConnection dbc;
    Connection conn=null;
    
    String ss1="",stamt="0";
    void getbillno()
    {
     try
        {
            Statement st=conn.createStatement();
            rs=st.executeQuery("select distinct bill_no from purchase");
            int count=0;
            while(rs.next())
            {
                count++;
            }
            txtpurbillno.setText(""+(count+1));
        }
        catch(Exception e)
        {
            System.out.println("Error in Purchase(getbillno) "+e);
        }    
    }
    //C:\oraclexe\app\oracle\product\11.2.0\server\jdbc\lib\ojdbc5.jar //path of jar file to connect oracle
    public MainMenu() {
        this.dbc = new MyConnection();
        this.conn = dbc.connectme();
        initComponents();
         getbillno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnprdsall = new javax.swing.JButton();
        btnbtlin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprdid = new javax.swing.JTextField();
        txtprdname = new javax.swing.JTextField();
        txtprdstock = new javax.swing.JTextField();
        txtprdprice = new javax.swing.JTextField();
        btnshow = new javax.swing.JButton();
        btnprdins = new javax.swing.JButton();
        btnprddel = new javax.swing.JButton();
        btnprdupdt = new javax.swing.JButton();
        btmcancel = new javax.swing.JButton();
        btncheckexp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtqserch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnpur = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtpurbillno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpurarea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblpuramt = new javax.swing.JLabel();
        txtpurmedid = new javax.swing.JTextField();
        txtpurqty = new javax.swing.JTextField();
        btnpurok = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtbillno = new javax.swing.JTextField();
        btnbillok = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        lblbilltotamt = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "name", "Quantity", "MRP", "MFG", "EXP"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("    MEDICINE LIST");

        btnprdsall.setText("LOAD MEDICINE LIST");
        btnprdsall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprdsallActionPerformed(evt);
            }
        });

        btnbtlin.setText("BACK TO LOG IN");
        btnbtlin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtlinActionPerformed(evt);
            }
        });

        jLabel2.setText("MEDICINE ID");

        jLabel3.setText("TITLE");

        jLabel4.setText("QNT");

        jLabel5.setText("MRP per piece");

        jLabel6.setText("MFD");

        jLabel7.setText("EXD");

        btnshow.setText("OK");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnprdins.setText("INSERT");
        btnprdins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprdinsActionPerformed(evt);
            }
        });

        btnprddel.setText("DELETE");
        btnprddel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprddelActionPerformed(evt);
            }
        });

        btnprdupdt.setText("UPDATE");
        btnprdupdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprdupdtActionPerformed(evt);
            }
        });

        btmcancel.setText("CANCEL");
        btmcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmcancelActionPerformed(evt);
            }
        });

        btncheckexp.setText("RM EXP PRD");
        btncheckexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckexpActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("  PHARMACY MANAGEMENT SYSTEM");

        txtqserch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqserchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnprdsall)
                                .addGap(39, 39, 39)
                                .addComponent(txtqserch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbtlin))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprdstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprdprice))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnprdupdt)
                                    .addComponent(btnprddel)
                                    .addComponent(btnprdins)
                                    .addComponent(btnshow)
                                    .addComponent(btmcancel)
                                    .addComponent(btncheckexp))))))
                .addGap(24, 24, 24))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btmcancel, btncheckexp, btnprddel, btnprdins, btnprdupdt, btnshow, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtprdid, txtprdname, txtprdprice, txtprdstock});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnprdsall)
                            .addComponent(btnbtlin)
                            .addComponent(txtqserch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnshow)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnprdins)
                                        .addGap(21, 21, 21)
                                        .addComponent(btnprddel)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnprdupdt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtprdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtprdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtprdstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtprdprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(btmcancel))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(btncheckexp))))
                        .addGap(261, 261, 261))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btmcancel, btncheckexp, btnprddel, btnprdins, btnprdupdt, btnshow, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtprdid, txtprdname, txtprdprice, txtprdstock});

        jTabbedPane1.addTab("Products", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(925, 5));
        jPanel2.setLayout(null);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MEDICINE LIST");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 61, 388, 34);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MED ID", "NAME", "QTY", "MRP"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 95, 388, 270);

        btnpur.setText("LOAD MEDICINE LIST");
        btnpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpurActionPerformed(evt);
            }
        });
        jPanel2.add(btnpur);
        btnpur.setBounds(10, 380, 135, 45);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BILL NO");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(429, 61, 79, 34);

        txtpurbillno.setEditable(false);
        txtpurbillno.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtpurbillno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpurbillno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpurbillno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtpurbillno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpurbillnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtpurbillno);
        txtpurbillno.setBounds(545, 61, 92, 34);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TITLE");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(429, 95, 79, 39);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("QNT");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(545, 97, 92, 35);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AMOUNT");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(770, 96, 65, 38);

        txtpurarea.setColumns(20);
        txtpurarea.setRows(5);
        jScrollPane3.setViewportView(txtpurarea);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(429, 140, 406, 184);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("GROSS AMT");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(429, 335, 141, 54);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MED ID");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(435, 407, 135, 54);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("QNT");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(429, 472, 135, 54);

        lblpuramt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpuramt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblpuramt);
        lblpuramt.setBounds(570, 340, 135, 54);

        txtpurmedid.setText("0");
        jPanel2.add(txtpurmedid);
        txtpurmedid.setBounds(574, 407, 135, 54);

        txtpurqty.setText("0");
        jPanel2.add(txtpurqty);
        txtpurqty.setBounds(574, 472, 135, 54);

        btnpurok.setText("OK");
        btnpurok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpurokActionPerformed(evt);
            }
        });
        jPanel2.add(btnpurok);
        btnpurok.setBounds(720, 350, 110, 36);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("MEDICINE PURCHASING");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 11, 839, 39);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(280, 380, 90, 40);

        jTabbedPane1.addTab("Purchese", jPanel2);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("BILL DETAILS");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ENTER BILL NO");

        txtbillno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnbillok.setText("OK");
        btnbillok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillokActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MED ID", "NAME", "QTY", "MRP", "AMOUNT"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("TOTAL AMT");

        lblbilltotamt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbilltotamt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Generate Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblbilltotamt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)
                                        .addComponent(txtbillno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                                        .addComponent(btnbillok, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(79, 79, 79))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbillno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbillok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblbilltotamt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bill", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpurActionPerformed
        // TODO add your handling code here:
        try
        {
            Statement st=conn.createStatement();
            rs=st.executeQuery("select * from prod order by prd_id");
            String aa="";
            String sprd_id;
            String sname;
            String sstock;
            String sprice;
            DefaultTableModel tm=(DefaultTableModel)jTable2.getModel();
            while(true)
            {
                int c=tm.getRowCount();
                if(c==0)
                    break;
                else
                    tm.removeRow(0);
            }
            while(rs.next())
            {
                sprd_id=rs.getString(1);
                sname=rs.getString(2);
                sstock=rs.getString(3);
                sprice=rs.getString(4);
                Object kk[]={sprd_id,sname,sstock,sprice};
                tm.addRow(kk);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection"+e);
        }
    }//GEN-LAST:event_btnpurActionPerformed

    private void btnprdsallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprdsallActionPerformed
        // TODO add your handling code here:
        try
        {
            Statement st=conn.createStatement();
            rs=st.executeQuery("select * from prod order by prd_id");
            String aa="";
            String sprd_id;
            String sname;
            String sstock;
            String sprice;
            String manufdate;
            String expdate;
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while(true)
            {
                int c=tm.getRowCount();
                if(c==0)
                    break;
                else
                    tm.removeRow(0);
            }
            while(rs.next())
            {
                sprd_id=rs.getString(1);
                sname=rs.getString(2);
                sstock=rs.getString(3);
                sprice=rs.getString(4);
                manufdate=rs.getString(5);
                expdate=rs.getString(6);
                Object kk[]={sprd_id,sname,sstock,sprice,manufdate,expdate};
                tm.addRow(kk);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection"+e);
        }
    }//GEN-LAST:event_btnprdsallActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        try
        {
            sel=conn.prepareStatement("select * from prod where prd_id=?");
            int pid=Integer.parseInt(txtprdid.getText());
            sel.setInt(1, pid);
            
            
            sel.executeQuery();
            
            rs=sel.getResultSet();
             if(rs.next())
            {
                txtprdname.setText(rs.getString("sname"));
                txtprdstock.setText(rs.getString("stock"));
                txtprdprice.setText(rs.getString("price"));
                txtprdexpdt.setDate(rs.getDate("manufdate"));
                txtprdexpdt.setDate(rs.getDate("expdate"));
            }
             else
             {
                JOptionPane.showMessageDialog(null,"this record does not existed");
                
             }
             
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"error in connection"+ e);

        }
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnprdinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprdinsActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            sel=conn.prepareStatement("insert into prod(prd_id,sname,stock,price,manufdate,expdate)values(?,?,?,?,?,?)");
            int prdid=Integer.parseInt(txtprdid.getText());
            String name=txtprdname.getText();
            int stock=Integer.parseInt(txtprdstock.getText());
            int mrp=Integer.parseInt(txtprdprice.getText());
            Date prddt=new Date(txtprdexpdt.getDate().getTime());
            Date prdexdt=new Date(txtprdexpdt.getDate().getTime());
            
            
            sel.setInt(1,prdid);
            sel.setString(2,name);
            sel.setInt(3,stock);
            sel.setInt(4,mrp);
            sel.setDate(5,prddt);
            sel.setDate(6,prdexdt);
            
            int i=sel.executeUpdate();
            if(i>0)
               JOptionPane.showMessageDialog(null,"record inserted successfully"); 
            else
                JOptionPane.showMessageDialog(null, "failed inseted");
            sel.clearParameters();
            btnprdsallActionPerformed(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnprdinsActionPerformed

    private void txtprdmfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprdmfgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprdmfgActionPerformed

    private void btnbtlinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtlinActionPerformed
        // TODO add your handling code here:
        new MedicRemaster().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnbtlinActionPerformed

    private void btncheckexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckexpActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.util.Date check=new java.util.Date();
            SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy");
            String s=f.format(check);
            System.out.println(s);
            Statement st=conn.createStatement();
            ResultSet rs1=st.executeQuery("delete from prod where expdate<to_date('"+s+"','dd/MM/yyyy')");
            btnprdsallActionPerformed(null);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btncheckexpActionPerformed

    private void btnprdupdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprdupdtActionPerformed
        // TODO add your handling code here:
        try
        {
            sel=conn.prepareStatement("update prod set sname=?,price=?,stock=?,manufdate=?,expdate=? where prd_id=?");
            sel.setInt(6,Integer.parseInt(txtprdid.getText()));
            sel.setString(1,txtprdname.getText());
            sel.setInt(2,Integer.parseInt(txtprdprice.getText()));
            sel.setInt(3,Integer.parseInt(txtprdstock.getText()));
            sel.setDate(4,new Date(txtprdexpdt.getDate().getTime()));
            sel.setDate(5,new Date(txtprdexpdt.getDate().getTime()));
            int i=sel.executeUpdate();
            if(i>0)
                JOptionPane.showMessageDialog(null,"record updated successfully");
            else
            {
                JOptionPane.showMessageDialog(null,"failed updation");
                resettxt(null);
            }
            btnshowActionPerformed(null);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnprdupdtActionPerformed

    private void btmcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmcancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btmcancelActionPerformed

    private void btnpurokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpurokActionPerformed
        // TODO add your handling code here:
        String name="",qty="",price="",samt="";
        int prd_id=0,qy=0;
        
        prd_id=Integer.parseInt(txtpurmedid.getText());
        qy=Integer.parseInt(txtpurqty.getText());
        if(prd_id==0||qy==0)
        {
           JOptionPane.showMessageDialog(null,"please Enter some values");
           return;
        }
        PreparedStatement pstmt=null;
        try
        {
            pstmt=conn.prepareStatement("select * from prod where prd_id=?");
            pstmt.setString(1,prd_id+"");
            rs=pstmt.executeQuery();
            while(rs.next())
            {
                prd_id=rs.getInt("prd_id");
                name=rs.getString("sname");
                qty=rs.getString("stock");
                price=rs.getString("price");
            }
            pstmt.clearParameters();
            int pr,a=0;
            pr=Integer.parseInt(price);
            a=pr*qy;
            int t_stamt=Integer.parseInt(stamt)+a;
            stamt=""+t_stamt;
            ss1=ss1+name+"                                   "+qy+"                                 "+a+"\n";
            samt=samt+a;
            pstmt=conn.prepareStatement("insert into purchase(bill_no,medicine_id,medicine_name,quantity,price,amount) values (?,?,?,?,?,?)");
            pstmt.setString(1,txtpurbillno.getText());
            pstmt.setInt(2,prd_id);
            pstmt.setString(3,name);
            pstmt.setInt(4,qy);
            pstmt.setString(5,price);
            pstmt.setString(6,samt);
            int i=pstmt.executeUpdate();
            pstmt.clearParameters();

            pstmt=conn.prepareStatement("update prod set stock=stock-? where prd_id=?");
            pstmt.setString(1,qy+"");
            pstmt.setString(2,prd_id+"");
            rs=pstmt.executeQuery();
            pstmt.clearParameters();
            
            if(i>0)
                JOptionPane.showMessageDialog(null,"Record Inserted");
            else
                JOptionPane.showMessageDialog(null,"Error in Record Insert");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
        }
        txtpurmedid.setText("");
        txtpurqty.setText("");
        txtpurarea.setText(ss1);
        lblpuramt.setText(stamt);
        btnpurActionPerformed(null);
    }//GEN-LAST:event_btnpurokActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        btmcancelActionPerformed(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbillokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillokActionPerformed
        // TODO add your handling code here:
        int tmt=0;
        try
        {
            Statement stm=conn.createStatement();
            rs=stm.executeQuery("select * from purchase where bill_no="+txtbillno.getText());
            String prd_id,name,qty,price,amt;
            DefaultTableModel tm=(DefaultTableModel)jTable3.getModel();
            while(true)
            {
                int c=tm.getRowCount();
                if(c==0)
                    break;
                else
                    tm.removeRow(0);
            }
            int flag=0;
            while(rs.next())
            {
                flag=1;
                prd_id=rs.getString(2);
                name=rs.getString(3);
                qty=rs.getString(4);
                price=rs.getString(5);
                amt=rs.getString(6);
                Object kk[]={prd_id,name,qty,price,amt};
                tm.addRow(kk);
                tmt=tmt+Integer.parseInt(amt);
            }
            lblbilltotamt.setText(""+tmt);
            if(flag==0)
                JOptionPane.showMessageDialog(null,"No Record Found");
            getbillno();
            txtpurarea.setText(null);
        }
        catch(Exception e)
        {
            System.out.println("Error in Bill(Ok Button) "+e);
        }
    }//GEN-LAST:event_btnbillokActionPerformed

    private void txtqserchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqserchKeyTyped
        // TODO add your handling code here:
        try
        {
            sel=conn.prepareStatement("select * from prod where sname like ?");
            String jb=txtqserch.getText();
            sel.setString(1,jb+"%");
            rs=sel.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            int prd_id,stock,mrp;
            String name,expdate,mfg;
            
            while(true)
            {
                int c=tm.getRowCount();
                if(c==0)
                    break;
                tm.removeRow(0);
            }
            while(rs.next())
            {
                prd_id=rs.getInt("prd_id");
                name=rs.getString("sname");
                stock=rs.getInt("stock");
                mrp=rs.getInt("price");
                mfg=rs.getString("manufdate");
                expdate=rs.getString("expdate");
                Object kk[]={prd_id,name,stock,mrp,mfg,expdate};
                tm.addRow(kk);
            }
            
        }//end of try
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_txtqserchKeyTyped

    private void btnprddelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprddelActionPerformed
        // TODO add your handling code here:
        int ans=JOptionPane.showConfirmDialog(null,"Surely Want to Update?");
       if(ans==JOptionPane.YES_OPTION)
       {
        try
        {
            PreparedStatement pstmt=null;
            pstmt=conn.prepareStatement("delete from prod where prd_id=?");
            int medid=Integer.parseInt(txtprdid.getText());
            pstmt.setInt(1,medid);
            int i=pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null,"One Record Deleted");
                resettxt(null);
            }           
            else
                JOptionPane.showMessageDialog(null,"Error in Record Delete");
            pstmt.clearParameters();
            btnprdsallActionPerformed(null);
        }
        catch(Exception e)
        {
            System.out.println("Error in Product(Delete Button) "+e);
        }
       }
    }//GEN-LAST:event_btnprddelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        btmcancelActionPerformed(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                try
        {
            generateReport();
        }
        catch(Exception e)
        {
            System.out.println("Error in Bill Code(Generate Report Button) "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtpremfgdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpremfgdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpremfgdtActionPerformed

    private void txtpurbillnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpurbillnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpurbillnoActionPerformed
     private void generateReport() {
        String shopname="M.E.S.A Dragon pvt.lmt.";
        String shopaddress="Yadunandan nagar, Tifra";
        String phoneno="8827123300, 8770275331";
        DefaultTableModel model1= (DefaultTableModel) jTable1.getModel();
        int sel_row= jTable1.getSelectedRow();
        MyConnection obj=new MyConnection();
        Connection conn=obj.connectme();


        StyleBuilder boldStyle = stl.style().bold();

        StyleBuilder subtotalStyle = stl.style(boldStyle).setTopBorder(stl.pen1Point()).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER);

        StyleBuilder boldCenteredStyle;

        StyleBuilder bold22CenteredStyle = stl.style(boldStyle).setTextAlignment(HorizontalTextAlignment.CENTER, VerticalTextAlignment.MIDDLE).setFontSize(22);

        boldCenteredStyle = stl.style(boldStyle).setHorizontalTextAlignment(HorizontalTextAlignment.CENTER);

        StyleBuilder columnTitleStyle = stl.style(boldCenteredStyle).setBorder(stl.pen1Point()).setBackgroundColor(Color.LIGHT_GRAY);

        TextColumnBuilder<Integer> quantityColumn=Columns.column("Quantity", "quantity", DataTypes.integerType());

        TextColumnBuilder<Integer> priceColumn=Columns.column("Per Unit Price", "price", DataTypes.integerType());

        TextColumnBuilder<BigDecimal> totalColumn = priceColumn.multiply(quantityColumn).setTitle("Price");

        String query = "select medicine_name, quantity, price from purchase where bill_no="+txtbillno.getText();

        JasperReportBuilder report = DynamicReports.report();//a new report

        report.setColumnTitleStyle(columnTitleStyle).setColumnStyle(boldCenteredStyle)

         .columns(Columns.column("Medicine", "medicine_name", DataTypes.stringType()),quantityColumn,priceColumn,totalColumn)

         .title(  //title of the report
                 Components.text(("REPORT GENERATION")).setStyle(bold22CenteredStyle),
                 Components.text("BILL NO - "+txtbillno.getText()),
                 cmp.horizontalList().setStyle(stl.style(10)).setGap(50).add(
                 cmp.hListCell(createCustomerComponent("SHOP INFORMATION ",shopname,shopaddress,phoneno,2))),cmp.verticalGap(10)
                 .setStyle(boldCenteredStyle))

         .subtotalsAtSummary(sbt.sum(totalColumn).setLabel("Total :").setStyle(subtotalStyle))

         .pageFooter(Components.pageXofY())//show page number on the page footer

         .setDataSource(query,conn);
        try 
        {
            report.show();
                        //show the report
                        //export the report to a pdf file
                        //report.toPdf(new FileOutputStream("c:/report.pdf"));
        } 
        catch (DRException e) 
        {
            e.printStackTrace();
            System.out.println("Error in generatereport "+e);
        }
        catch (Exception e) 
        {
            System.out.println("Error in generatereport "+e);
        }
}
     private ComponentBuilder<?, ?> createCustomerComponent(String label, String cname, String value,String pn, Integer i) 
{
        HorizontalListBuilder list = cmp.horizontalList().setBaseStyle(stl.style().setTopBorder(stl.pen1Point()).setLeftPadding(10));

        addCustomerAttribute(list, "Name ", cname);

        addCustomerAttribute(list, "Address", value);

        addCustomerAttribute(list, "Phone No.", pn);

        return cmp.verticalList(cmp.text(label).setStyle(Templates.boldStyle),list);
}

private void addCustomerAttribute(HorizontalListBuilder list, String label, String value) 
{
    if (value != null) 
    {
    list.add(cmp.text(label + ":").setFixedColumns(8).setStyle(Templates.boldStyle), cmp.text(value)).newRow();
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }
    private void resettxt(Object object) {
           //To change body of generated methods, choose Tools | Templates.
           txtprdid.setText(null);
           txtprdname.setText(null);
           txtprdstock.setText(null);
           txtprdprice.setText(null);
           txtpremfgdt.setDate(null);
           txtprdexpdt.setDate(null);
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmcancel;
    private javax.swing.JButton btnbillok;
    private javax.swing.JButton btnbtlin;
    private javax.swing.JButton btncheckexp;
    private javax.swing.JButton btnprddel;
    private javax.swing.JButton btnprdins;
    private javax.swing.JButton btnprdsall;
    private javax.swing.JButton btnprdupdt;
    private javax.swing.JButton btnpur;
    private javax.swing.JButton btnpurok;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblbilltotamt;
    private javax.swing.JLabel lblpuramt;
    private javax.swing.JTextField txtbillno;
    private javax.swing.JTextField txtprdid;
    private javax.swing.JTextField txtprdname;
    private javax.swing.JTextField txtprdprice;
    private javax.swing.JTextField txtprdstock;
    private javax.swing.JTextArea txtpurarea;
    private javax.swing.JTextField txtpurbillno;
    private javax.swing.JTextField txtpurmedid;
    private javax.swing.JTextField txtpurqty;
    private javax.swing.JTextField txtqserch;
    // End of variables declaration//GEN-END:variables

   
}
